version: "3"
services:
    debian_python3_ssh:
        stdin_open: true
        tty: true
        restart: always
        container_name: scanproxy
        networks:
            - rfid_net
        environment:
            - SERVICE_CONFIG={"STATUS_REPORT_TIMEOUT_S":7,"DATA_REPORT_TIMEOUT_S":10,"DATA_REPORT_INTERVAL_S":30,"STATUS_REPORT_INTERVAL_S":600,"READER_IP":"192.168.0.155","READER_POWER":[25],"STATUS_ENDPOINT":"https://ONETIMEproxydev.azurewebsites.net/api/v1/statusevent","DATA_ENDPOINT":"https://ONETIMEproxydev.azurewebsites.net/api/v1/tagevent","SECRET_CHARACTER_KEY":"7Bf5mdnVt2SCMEvgFcJMk2rk20DVHj"}
        volumes:
            - /app:/app
        ports:
            - "22"
        image: stevenli2019/debian_python3_ssh
        command: bash #/sbin/entrypoint.sh
networks:
    rfid_net:
        ipam: 
            config:
                - subnet: 192.168.10.0/24
           
       