version: '3'
services:
    debian_python3_ssh:
        stdin_open: true
        tty: true
        restart: always
        container_name: scanproxy
        networks:
            - rfid_net
        environment:
            - SERVICE_CONFIG={"STATUS_REPORT_TIMEOUT_S":7,"DATA_REPORT_TIMEOUT_S":10,"DATA_REPORT_INTERVAL_S":30,"STATUS_REPORT_INTERVAL_S":600,"READER_IP":"172.17.0.1","READER_API_PORT":5000,"READER_WS_PORT":7681,"READER_POWER":[25],"STATUS_ENDPOINT":"https://xxx.xxx.xxx/api/v1/statusevent","DATA_ENDPOINT":"https://xxx.xxx.xxx/api/v1/tagevent","SECRET_CHARACTER_KEY":"7Bf5mdnVt2SCMEvgFcJMk2rk20DVHj"}
        volumes:
            - /app:/app
        ports:
            - "22"
        logging:
            driver: "json-file"
            options:
                max-size: 10m
                max-file: "3"      
        image: stevenli2019/xcrf868_scanproxy:arm
        command: bash /sbin/entrypoint.sh
networks:
    rfid_net:
        external: false
